gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
models/piana/bench01.mdl
models/piana/escooter.mdl
models/piana/flag.mdl
models/piana/metro_sign4.mdl
models/piana/p_tree01.mdl
models/piana/trash_trashcan2.mdl
sound/piana/k_b_fire.wav
sound/piana/pianof.wav
sound/piana/wilhelm.wav
sprites/glow01.spr
sprites/xsmoke1.spr
sprites/xsmoke3.spr
