; API
api_rounds.amxx
api_custom_weapons.amxx
api_custom_entities.amxx
api_player_dizziness.amxx

; Core
drunkgames.amxx
drunkgames_gameplay_fixes.amxx
drunkgames_gamerules.amxx
drunkgames_player.amxx
drunkgames_player_radio.amxx

; Entities
drunkgames_entity_bottle.amxx
drunkgames_entity_trigger_endround.amxx

; Weapons
drunkgames_weapon_bottle.amxx

; HUD
drunkgames_hud_player.amxx
drunkgames_hud_winmessage.amxx
drunkgames_hud_notifications.amxx
