; APIs
amxx-modding-kit/api_assets.amxx
amxx-modding-kit/api_rounds.amxx
amxx-modding-kit/api_custom_weapons.amxx
amxx-modding-kit/api_custom_entities.amxx
amxx-modding-kit/api_player_dizziness.amxx
amxx-modding-kit/api_entity_force.amxx

; Core
drunkgames/core/core.amxx
drunkgames/core/gamerules.amxx
drunkgames/core/hud.amxx

; Features
drunkgames/features/notifications.amxx

; Entities
drunkgames/entities/bottle.amxx
drunkgames/entities/trigger_endround.amxx
drunkgames/entities/extensions/ambient_generic.amxx
drunkgames/entities/extensions/func_button.amxx
drunkgames/entities/extensions/func_door.amxx
drunkgames/entities/extensions/func_train.amxx
drunkgames/entities/extensions/func_wall_toggle.amxx
drunkgames/entities/extensions/multi_manager.amxx
drunkgames/entities/extensions/multisource.amxx

; Weapons
amxx-modding-kit/weapon_base_throwable.amxx
drunkgames/weapons/bottle.amxx
