#define DRUNKGAME_TITLE "Drunk Games"
#define DRUNKGAME_VERSION "0.9.0"

#define DRUNKGAME_CHAT_PREFIX "^4[Drunk Games]^1"

stock const DRUNKGAME_WEAPON_BOTTLE[] = "drunkgames/v090/weapon_bottle";

stock const DRUNKGAME_WEAPON_BOTTLE_HUD_TXT[] = "sprites/drunkgames/v090/weapon_bottle.txt";

stock const DRUNKGAME_MODEL_WEAPON_BOTTLE_V[] = "models/drunkgames/v090/weapons/v_bottle.mdl";
stock const DRUNKGAME_MODEL_WEAPON_BOTTLE_P[] = "models/drunkgames/v090/weapons/p_bottle.mdl";
stock const DRUNKGAME_MODEL_WEAPON_BOTTLE_W[] = "models/drunkgames/v090/weapons/w_bottle.mdl";
stock const DRUNKGAME_MODEL_BOTTLE_GIBS[] = "models/drunkgames/v090/gibs_bottle.mdl";

stock const DRUNKGAME_SOUND_BOTTLE_THROW[] = "drunkgames/v090/bottle_throw.wav";
stock const DRUNKGAME_SOUND_BOTTLE_HIT[] = "drunkgames/v090/bottle_break.wav";

stock const DRUNKGAME_SPRITE_HUD[][] = {
    "sprites/640hud2.spr",
    "sprites/640hud5.spr"
};
